// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo4Rl8gYEbLpfa8u05Qy-eq8GhQcnRb7g',
    appId: '1:685785561916:web:d5607edd570c54f5f8bc39',
    messagingSenderId: '685785561916',
    projectId: 'vektor-98115',
    authDomain: 'vektor-98115.firebaseapp.com',
    storageBucket: 'vektor-98115.firebasestorage.app',
    measurementId: 'G-BJGHTXTBTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR5aNYEcB_jzU4GFpQOEP90nl7ir4ZnrE',
    appId: '1:685785561916:android:b8f2913014ef1edcf8bc39',
    messagingSenderId: '685785561916',
    projectId: 'vektor-98115',
    storageBucket: 'vektor-98115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAEKr8puLGk94D5ZyWmQ3MiolcYlb2KOo',
    appId: '1:685785561916:ios:20b42c946a3ec556f8bc39',
    messagingSenderId: '685785561916',
    projectId: 'vektor-98115',
    storageBucket: 'vektor-98115.firebasestorage.app',
    iosBundleId: 'com.example.vektor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAEKr8puLGk94D5ZyWmQ3MiolcYlb2KOo',
    appId: '1:685785561916:ios:20b42c946a3ec556f8bc39',
    messagingSenderId: '685785561916',
    projectId: 'vektor-98115',
    storageBucket: 'vektor-98115.firebasestorage.app',
    iosBundleId: 'com.example.vektor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo4Rl8gYEbLpfa8u05Qy-eq8GhQcnRb7g',
    appId: '1:685785561916:web:b392d97fdd6dc3b1f8bc39',
    messagingSenderId: '685785561916',
    projectId: 'vektor-98115',
    authDomain: 'vektor-98115.firebaseapp.com',
    storageBucket: 'vektor-98115.firebasestorage.app',
    measurementId: 'G-GJB96GMH4B',
  );

}
